### PR TITLE
Update dependencies that can be updated safely

### PR DESCRIPTION
**Pull request by chadxz**
This updates all dependencies (dev and prod) except socket.io-client, which needs to stay as-is because the server is pre 1.0

Ran tests and they pass.

### CODE REVIEW

**Comment by tiandavis** [comment]
👍

**Comment by ruffrey** [comment]
:+1:

**Comment by erinspice** [comment]
Ship it!

**Comment by pho3nixf1re** [comment]
yay!!! Thank you for doing this maintenance task. That red badge has been bugging me.

**Pull request merged**
