### PR TITLE
Bugfix/url parsing

### PR DESCRIPTION
**Pull request by leedm777**
I started by just trying to fix URL building, and fixed a few other things in the process.

* Adding IntelliJ files to the .gitignore
* Doc and error message fixes for test config
* Replaced the string manipulation in client.js with URL building.

Building URLs by munging strings directly is usually problematic.
This patch makes the URL building more robust by parsing the baseURL and
rebuilding it in order to determine the Socket.io URL.

### CODE REVIEW

**Comment by chadxz** [comment]
looks fine to me. Build error doesn't seem related to the PR

**Comment by leedm777** [comment]
The build error is prob. b/c my TravisCI account doesn't have the encryption key to decrypt the default config.

**Comment by pho3nixf1re** [comment]
@leedm777 It should not matter if you have the key or not since Travis does and that is what is running the tests. It should only matter if you wish to run the tests locally using the settings that are in the encrypted config file. I'm not sure why this is causing an error after poking at it for a bit. Let me know if you need help understanding the TravisCI setup with the encrypted file.

**Comment by ruffrey** [comment]
As long as the tests run locally, i'm good with this. We probably just need a ticket to fix travis.

Thanks!

**Pull request merged**
